-- ============================================================================
-- SEBAWEB — İLETİŞİM MESAJLARI (EmailJS yerine kendi veritabanımız)
-- ============================================================================
-- AMAÇ: İletişim formu EmailJS'e (dolayısıyla kopabilen bir Gmail OAuth
--       yetkisine) bağlı olmasın. Mesaj doğrudan kendi Supabase projenize
--       yazılsın; siz yönetim panelinden okuyun. Hiçbir mesaj kaybolmaz.
--
-- GÜVENLİK MANTIĞI:
--     INSERT  -> herkes (siteyi gezen biri forma yazabilsin)  [anon + authenticated]
--     SELECT  -> YALNIZCA yönetici   (başkasının mesajını okuyamaz)
--     UPDATE  -> YALNIZCA yönetici   (okundu işaretleme)
--     DELETE  -> YALNIZCA yönetici
--
-- Yönetici, `projects` ve `news` tablolarındakiyle aynı kişidir ve aynı
-- yöntemle otomatik bulunur (en son giriş yapan kullanıcı).
--
-- ÇALIŞTIRMA: Supabase Dashboard -> SQL Editor -> New query
--             tamamını yapıştır -> RUN.  Tekrar çalıştırılabilir.
-- ============================================================================


-- ---------------------------------------------------------------------------
-- 0) TABLO
--    Uzunluk sınırları CHECK ile konuldu: form dışından gelen bozuk/aşırı
--    büyük kayıtlar veritabanı seviyesinde reddedilir.
-- ---------------------------------------------------------------------------
create table if not exists public.contact_messages (
  id         bigint generated by default as identity primary key,
  name       text        not null,
  email      text        not null,
  message    text        not null,
  is_read    boolean     not null default false,
  created_at timestamptz not null default now(),
  constraint contact_messages_name_uzunluk    check (char_length(name)    between 1 and 200),
  constraint contact_messages_email_uzunluk   check (char_length(email)   between 3 and 200),
  constraint contact_messages_email_bicim     check (position('@' in email) > 1),
  constraint contact_messages_message_uzunluk check (char_length(message) between 1 and 5000)
);

create index if not exists contact_messages_created_at_idx
  on public.contact_messages (created_at desc);


-- ---------------------------------------------------------------------------
-- 1) POLİTİKALAR
--    Otomatik seçim yanlış olursa `elle` değişkenine kendi e-postanızı yazın.
-- ---------------------------------------------------------------------------
do $$
declare
  elle        text := null;      -- örn: 'ornek@eposta.com'
  admin_uid   uuid;
  admin_email text;
  kosul       text;
  n           int;
  p           record;
begin
  select count(*) into n from auth.users where email is not null;

  if n = 0 then
    raise exception 'auth.users icinde e-postali kullanici yok. Once Authentication > Users > Add user ile yonetici kullanicisi olusturun.';
  end if;

  if elle is not null then
    select u.id, lower(u.email) into admin_uid, admin_email
      from auth.users u
     where lower(u.email) = lower(elle)
     limit 1;
    if admin_uid is null then
      raise exception 'Verdiginiz e-posta (%) auth.users icinde yok.', elle;
    end if;
  else
    select u.id, lower(u.email) into admin_uid, admin_email
      from auth.users u
     where u.email is not null
     order by (u.last_sign_in_at is null), u.last_sign_in_at desc nulls last, u.created_at
     limit 1;
  end if;

  raise notice '>> Yonetici olarak secilen: %  (uid: %)', admin_email, admin_uid;

  -- Eski politikaları kaldır (adı ne olursa olsun)
  for p in
    select policyname from pg_policies
     where schemaname = 'public' and tablename = 'contact_messages'
  loop
    execute format('drop policy %I on public.contact_messages', p.policyname);
    raise notice '>> kaldirildi: %', p.policyname;
  end loop;

  kosul := '( auth.uid() = ' || quote_literal(admin_uid::text) || '::uuid'
        || ' or lower(auth.jwt() ->> ''email'') = ' || quote_literal(admin_email) || ' )';

  execute 'alter table public.contact_messages enable row level security';

  -- Herkes mesaj gönderebilir — ama YALNIZCA ekleyebilir.
  execute 'create policy contact_insert on public.contact_messages for insert to anon, authenticated with check (true)';

  -- Okuma / işaretleme / silme yalnızca yöneticide.
  execute 'create policy contact_admin_select on public.contact_messages for select to authenticated using ' || kosul;
  execute 'create policy contact_admin_update on public.contact_messages for update to authenticated using ' || kosul || ' with check ' || kosul;
  execute 'create policy contact_admin_delete on public.contact_messages for delete to authenticated using ' || kosul;

  execute 'grant insert on public.contact_messages to anon, authenticated';
  execute 'grant select, update, delete on public.contact_messages to authenticated';
  execute 'grant usage, select on sequence public.contact_messages_id_seq to anon, authenticated';

  raise notice '>> contact_messages hazir: 1 ekleme + 3 yonetici politikasi';
  raise notice '>> kurulan kosul: %', kosul;
end $$;


-- ---------------------------------------------------------------------------
-- 2) DOĞRULAMA
-- ---------------------------------------------------------------------------
select c.relname as tablo, c.relrowsecurity as rls_aktif
from pg_class c
join pg_namespace n on n.oid = c.relnamespace
where n.nspname = 'public' and c.relname = 'contact_messages';

select policyname, cmd, roles, qual, with_check
from pg_policies
where schemaname = 'public' and tablename = 'contact_messages'
order by cmd;
-- Beklenen: contact_insert (INSERT, {anon,authenticated}) +
--           contact_admin_select / contact_admin_update / contact_admin_delete


-- ---------------------------------------------------------------------------
-- 3) KONTROL — mevcut mesaj sayısı
-- ---------------------------------------------------------------------------
select count(*) as mesaj_sayisi,
       count(*) filter (where not is_read) as okunmamis
from public.contact_messages;
